contest/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse

urlpatterns = [

    #path("newsfeedsindia/",views.newsfeedsindia,name="newsfeedsindia"),
    #path("newsfeedsci/",views.newsfeedsci,name="newsfeedsci"),
   
    path("comp",views.comp,name="comp"),
    path("pastcontest",views.pastcontest,name="pastcontest"),
    path("livecontest",views.livecontest,name="livecontest"),
    path("organised",views.organised,name="organised"),
    path("participated",views.participated,name="participated"),
    path("viewcontest/<int:id1>",views.viewcontest,name="viewcontest"),
    path("acceptsubmission",views.acceptsubmission,name="acceptsubmission"),
    path("verifysubmission",views.verifysubmission,name="verifysubmission"),
    path("organise",views.organise,name="organisecontest"),
    path("submit/<int:contestid>",views.submit,name="submitcontest"),
    path("checkallcontest",views.checkallcontest,name="checkallcontest"),

    #path("",views.index,name="index"),









    #path('addpost/',views.addpost,name="addpost"),
]
#urlpatterns += static(settings.MEDIA_URL,
#                              document_root=settings.MEDIA_ROOT)
#urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

udesign/urls.py
from django.contrib import admin
from django.urls import path,include
#from competition import views


from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse

from django.contrib.sitemaps.views import sitemap
#from .sitemaps import feedSitemap,StaticViewSitemap,messengerSitemap,profileinfoSitemap,TodoSitemap
from django.contrib.auth import views as auth_views
from contest import views 
#from community import views as communityviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contest/', include('contest.urls')),#
    path('community/', include('community.urls')),
    path("",views.index,name="index"),
    path('logoutuser/',views.logoutuser,name="logoutuser"),
    path('signupuser/',views.signupuser,name="signupuser"),
    path('loginuser/',views.loginuser,name="loginuser"),
    #path('loginuser/',views.loginuser,name="loginuser"),
    #path("signupuser",views.signupuser,name="signupuser"),
    #path('oauth/', include('social_django.urls', namespace='social')),

    path('oauth/', include('social_django.urls', namespace='social')),
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



contest/models.py
from django.db import models

# Create your models here.


from PIL import Image

from django.contrib.auth.models import User

#User._meta.get_field('email')._unique = True   for email to be unique
#from contest.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    dob = models.DateField(null=True, blank=True)
    is_seller=models.BooleanField(default=False,null=True)
    website=models.URLField(max_length=5000,blank=True,null=True)
    image=models.ImageField(upload_to='media/images/',blank=True,null=True)
    mobile = PhoneNumberField(blank=True,null=True)

class contestModel(models.Model):
	
	title=models.CharField(max_length=200,blank=True)
	organisedby=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
	description=models.TextField(blank=True)
	organiser_email = models.EmailField(max_length=254,blank=True,null=True)
	enddate = models.DateField(blank=True,null=True)
	#about=models.TextField(blank=True,null=True)#it means having blank memeo is totally fine
	#created=models.DateTimeField(auto_now_add=True,blank=True,Default=False)#it means that it fixes time of its creation and it couldnot be changed
	#once it is set it cannot be changed
	prize=models.IntegerField(null=True)
	#image=models.ImageField(upload_to='media/images/',blank=True,null=True)
	poster=models.ImageField(upload_to='media/images/',blank=True,null=True)
	guidlines= models.FileField(upload_to='media/pdf/', max_length=1000000000, blank=True,null=True)
	"""
	def save(self):
		super().save()  
		print("path is ",self.poster.path)
	"""
	

	

	def __str__(self):
		#print("guidlines path",self.guidlines.path)
		return self.title


class submissionModel(models.Model):
	#name=models.ForeignKey(User,on_delete=models.CASCADE) #username

	contest=models.ForeignKey(contestModel,on_delete=models.CASCADE) #username
	submittedby=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
	#title=models.CharField(max_length=200,blank=True)
	description=models.TextField(blank=True)
	participant_email = models.EmailField(max_length=254,blank=True,null=True)
	document= models.FileField(upload_to='media/pdf/', max_length=254, blank=True,null=True)

	

	def __str__(self):

		return str(self.contest)+" "+str(self.submittedby)




 #name=models.ForeignKey(User,on_delete=models.CASCADE) #username

 #title=models.ForeignKey(User,on_delete=models.CASCADE) #username

contest/forms.py
from django.forms import ModelForm
from .models import submissionModel,contestModel
from django.contrib.auth.models import User
from contest.models import CustomUser

#this class is created so that to provide form for adding todo
#from phonenumber_field.formfields import PhoneNumberField
#class ClientForm(forms.Form):
from django import forms
class submissionForm(ModelForm):
    #specify what class and what model it would be working with
    class Meta:#specify what class we are working with
        model=submissionModel
        #mobile = PhoneNumberField()
        fields=['description','participant_email','document']#these are feature from model that we will set
        """
        widgets = {
            'participant_email': forms.EmailInput(attrs={'placeholder': 'Your email'}),
            'description': forms.TextInput(attrs={'placeholder': 'Your description'}),
        """
class DateInput(forms.DateInput):
    input_type = 'date'
class organisecontestForm(ModelForm):
    #specify what class and what model it would be working with
    class Meta:#specify what class we are working with
        model=contestModel
        #mobile = PhoneNumberField()
        fields=['title','description','organiser_email','enddate','prize','guidlines','poster']#these are feature from model that we will set
        widgets = {
            'enddate': DateInput(),
        }

class organiserdetailsForm(ModelForm):
    #specify what class and what model it would be working with
    class Meta:#specify what class we are working with
        model=CustomUser
        #mobile = PhoneNumberField()
        fields=['bio','location','website','mobile','image']#these are feature from model that we will set
      

contest/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect, get_object_or_404

from django.contrib.auth import login,logout ,authenticate
#from django.contrib.auth.models import User
from contest.models import CustomUser #custom user
from django.db import IntegrityError
from django.contrib import messages
from .models import contestModel,submissionModel

from .forms import submissionForm,organisecontestForm,organiserdetailsForm

from django.contrib.auth.decorators import login_required
from datetime import datetime,date
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string

def comp(request):
	#today_min = datetime.combine(date.today(), datetime.time.min)
	allcontest=contestModel.objects.all()
	return render(request, "contest/contest_home.html",{"allcontests":allcontest})
@login_required
def participated(request):
	#today_min = datetime.combine(date.today(), datetime.time.min)

	allcontest=contestModel.objects.filter(submissionmodel__submittedby=request.user)
	return render(request, "contest/contest_home.html",{"allcontests":allcontest})
@login_required
def organised(request):
	#today_min = datetime.combine(date.today(), datetime.time.min)
	if request.user.is_seller:
		allcontest=contestModel.objects.filter(organisedby=request.user)
		return render(request, "contest/contest_home.html",{"allcontests":allcontest})
	else:
		messages.success(request, 'You have not organised any contest ,You need to fill these detail for registering as contest organiser')
		return render(request, "contest/fill_seller_details.html",{'form':organiserdetailsForm()})

def livecontest(request):
	#today_min = datetime.combine(date.today(), datetime.time.min)
	allcontest=contestModel.objects.filter(enddate__gte =  date.today())
	return render(request, "contest/contest_home.html",{"allcontests":allcontest})
def pastcontest(request):
	#today_min = datetime.combine(date.today(), datetime.time.min)
	allcontest=contestModel.objects.filter(enddate__lt =  date.today())
	return render(request, "contest/contest_home.html",{"allcontests":allcontest})

	#return render(request, "contest/comp.html")
def checkallcontest(request):
	allcontest=contestModel.objects.all()
	return render(request, "contest/checkallcontest.html",{"allcontests":allcontest})
@login_required
def acceptsubmission(request):

	#allcontest=contestModel.objects.filter(organisedby=request.user)
	#return render(request, "contest/accept_submission.html",{"allsubmission":allcontest})
	if request.user.is_seller:
		allsubmission=submissionModel.objects.filter(contest__organisedby=request.user)

		return render(request, "contest/accept_submission.html",{"allsubmission":allsubmission})
	else:
		messages.success(request, 'You have not organised any contest ,You need to fill these detail for registering as contest organiser')
		return render(request, "contest/fill_seller_details.html",{'form':organiserdetailsForm()})

@login_required
def verifysubmission(request):

	#allcontest=contestModel.objects.filter(organisedby=request.user)
	#return render(request, "contest/accept_submission.html",{"allsubmission":allcontest})
	allsubmission=submissionModel.objects.filter(submittedby=request.user)

	return render(request, "contest/verify_submission.html",{"allsubmission":allsubmission})

def index(request):
	return render(request, "contest/index.html")
def logoutuser(request):

		if request.method=='POST' and request.user.is_authenticated:

				logout(request)
				return redirect('index')
				#return render(request,"posts/loginuser.html",{'form':AuthenticationForm()})
def logoutuser(request):

		if request.method=='POST' and request.user.is_authenticated:

				logout(request)
				return redirect('index')
def loginuser(request):
		if request.method== 'GET' :
                        print("GET METHOD")

                        return render(request,"contest/loginuser.html",{'form':AuthenticationForm()})

		elif request.method=='POST':
			user =authenticate(request,username=request.POST['username'], password=request.POST['password'])
			if user is None:
				messages.success(request, 'Account donot exist')

				return redirect("index")

									  #if user is none send them to same page with error
			else:
									  #login
				login(request,user)
				#messages.success(request, 'Welcome'+user.first_name)
				next=""
				if request.GET:

					next = request.GET['next']
				if next == "":
					return redirect('index')

				else:
					return redirect(next)
											#return HttpResponseRedirect(request.GET['next'])
											#return render(request,"posts/home.html",{"form":seeprofileForm()})

		else:
			messages.success(request, 'GET Method not allowed')

		return redirect("index")

def signupuser(request):
    if request.method== 'GET' :
                        print("GET METHOD")

                        return render(request,"contest/signupuser.html")
    elif request.method=="POST":


    		if request.POST['psw']==request.POST['psw-repeat']:
    			try:

    				user=CustomUser.objects.create_user( username=request.POST['email'], password=request.POST['psw'],email= request.POST['email'] )
    				name=request.POST['name']
    				user.first_name=name.split()[0]
    				user.last_name=name.split()[-1]

    				user.save()
    				return redirect("index")
    			except IntegrityError:
    				messages.success(request, 'Account with this email exist,choose another email or login')

    				return redirect("index")
    		else:
    				messages.success(request, 'Password donot match please try again')
    				return redirect("index")

    				#return render(request,"contest/index.html")




	#return render(request, "community/about.html")
def viewcontest(request,id1):
	if request.method =="GET": #when user first visit form show the form

				contest1=contestModel.objects.get(pk=id1)
				live=date.today()<=contest1.enddate
				return render(request,"contest/contest_detail.html",{'form':submissionForm(),"live":live,"contest":contest1})

@login_required
def organise(request):
	if request.user.is_seller:

			if request.method=="GET":
				return render(request, "contest/organise_contest.html",{'form':organisecontestForm()})

			elif request.method=="POST":

				form=organisecontestForm(request.POST,request.FILES)
				if form.is_valid():
					newcontest=form.save(commit=False)
					newcontest.organisedby=request.user
					newcontest.save()
					messages.success(request, 'contest organised with'+str(request.POST['title']))
					return render(request, "contest/index.html")
				else:
					messages.success(request, 'data not valid'+str(request.POST['title']))
					return render(request, "contest/index.html")
	else:
			if request.method=="GET":
				messages.success(request, 'You need to fill these detail for registering as contest organiser')
				return render(request, "contest/fill_seller_details.html",{'form':organiserdetailsForm()})

			elif request.method=="POST":
			        try:
        				user_object=CustomUser.objects.get(username=request.user.username)
        				if request.POST['bio']:
        					user_object.bio=request.POST['bio']
        				if request.POST['location']:
        					user_object.location=request.POST['location']
        				if request.POST['website']:
        					user_object.website=request.POST['website']
        				if request.FILES['image']:
        					user_object.image=request.FILES['image']
        				if request.POST['mobile']:
        					user_object.mobile=request.POST['mobile']
        				user_object.save()
        				messages.success(request, 'Thank you choosing us, we will verify your details and contact you ')
        				mail_subject = 'Request for oranising contest on vdesign'
        				message = render_to_string('contest/request_organise_contest_email.html',{'image': request.FILES['image'],'email' : request.user.email,'name': str(request.user.first_name)+" "+str(request.user.last_name),'bio': request.POST['bio'],'location': request.POST['location'],'mobile': request.POST['mobile'],'website': request.POST['website']})
        				to_email1='prashant09.thakur@gmail.com'

        				to_email3='anvesh.ashwin@gmail.com'
        				if request.user.email:
        				    to_email4=request.user.email
        				else:
        				    to_email4='prashantt.ug17.cs@nitp.ac.in'


        				email = EmailMessage(mail_subject, message, to=[to_email1,to_email3,to_email4])
        				email.send()
        				return render(request, "contest/index.html")
        			except:
        			    messages.success(request, 'All field required')
        			    return render(request, "contest/fill_seller_details.html",{'form':organiserdetailsForm()})





@login_required
def submit(request,contestid):
		if request.method =="GET": #when user first visit form show the form
				contest1=contestModel.objects.get(pk=contestid)
				return render(request,"contest/participate_contest.html",{'form':submissionForm(),"contest":contest1})

		elif request.method =="POST": #when user first visit form show the form





						contest1=contestModel.objects.get(pk=contestid)
						form=submissionForm(request.POST,request.FILES)

						newcontest=form.save(commit=False)
						#if request.user.is_authenticated:
							   #newtodo.user_new=request.user
							   #in newtodo user field is missing
						newcontest.submittedby=request.user
						newcontest.contest=contest1
						newcontest.save()
							#person2.save()
						messages.success(request,"your submission will be considered")
						return render(request, "contest/index.html")

contest/templates/contest/fill_seller_details.html
{% extends 'contest/base.html' %}

{% block content %}
{% if error %}
<script type="text/javascript">
  alert('{{error}}')
</script>
   {% endif %}


<style type="text/css">

body {
 /* background-image: url('https://cdn.dribbble.com/users/722246/screenshots/11096994/media/abcf2fe91c135bbaec19a3816dd0a992.gif');
  background-repeat: repeat-y;
  background-size: 100vw 100vh;*/
  background-color: #f6f6f6;
  margin-top: 0vw;
  color: white;
}

  #t
  {
       background-color : black;
      color :white;

       margin-left: 0vw;
      margin-top: 0vh;
      width: 60vw;
      border-radius:45px;
  }



  .flex-container_up{
    display: flex;
    margin: 5vw;
    margin-top: -2vh;
    padding-right: 3vw;
    align-items: space-between;
    background-color: #565656;

    align-content: center;
     flex-wrap: wrap;

  }

#id_location,#id_mobile,#id_website,#id_image
{
position: relative;
  width: 50vw;
  margin-left: 5vw;
  background-color :white;
        color :blue;
        border-radius:25px;

}
#id_bio
{
  position: relative;
  margin-left:5vw;
  width: 50vw;
  height: 20vh;
  border-radius:25px;

}

@media only screen and (max-width: 800px)
{

#id_location,#id_mobile,#id_website,#id_image
{
  position: relative;
  width: 70vw;
  margin-left: 10vw;
  background-color :white;
        color :blue;

}
#id_bio
{
  height: 20vw;
  background-color :white;
        color :blue;

}
  #t
    {
      margin-left: 10vw;
      width:70vw;
      margin-top: -5vh;
        font-size:0.7em;




    }
    #emaildes
    {
        font-size:0.5em;

    }



  }
    #emaildes
    {

        color:#565656;
    }

</style>
<h3 id="t" class="alert alert-success">REGISTER AS SELLER</h3>

{% if messages %}
<div class="alert alert-success alert-dismissible">
  {% for message in messages %}
    <p>{{ message }}</p>
  {% endfor %}
</div>
{% endif %}


<form method="POST" action="{% url 'organisecontest' %}"   style="color: white; "enctype="multipart/form-data">
  {% csrf_token %}










<br>
<p style="color:black;margin-left:5vw;">About You / Your Organisation</p>
<!--Full Name          :  &nbsp  &nbsp  --> {{form.bio}}
<br>
<!--email         : &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  --> {{form.location}}


<br>
<!--Address       : &nbsp &nbsp &nbsp &nbsp -->  {{form.website}}
<br>

<p style="color:black;margin-left:5vw;">Mobile No</p>
  {{form.mobile}}
<br>
<p style="color:black;margin-left:5vw;">Your Image</p>
 {{form.image}}
<br>

  <button  action="{% url 'organisecontest' %}" class="btn btn-success" style="margin-left:30vw;" type="submit">Update your details</button>

</form>
  <script>
            /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field
     */

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='bio..';
    form_fields[2].placeholder='location..';
    form_fields[3].placeholder='website..';

    form_fields[4].placeholder='mobile...';




    for (var field in form_fields){
      form_fields[field].className += ' form-control'
    }
  </script>

{% endblock %}

contest/templates/contest/organise_contest.html
{% extends 'contest/base.html' %}

{% block content %}
{% if error %}
<script type="text/javascript">
  alert('{{error}}')
</script>
   {% endif %}


<style type="text/css">

body {
 /* background-image: url('https://cdn.dribbble.com/users/722246/screenshots/11096994/media/abcf2fe91c135bbaec19a3816dd0a992.gif');
  background-repeat: repeat-y;
  background-size: 100vw 100vh;*/
  background-color: #f6f6f6;
  margin-top: 0vw;
  color: white;
}

  #t
  {
       background-color : black;
      color :white;

       margin-left: 0vw;
      margin-top: 0vh;
      width: 60vw;
      border-radius:45px;
  }



  .flex-container_up{
    display: flex;
    margin: 5vw;
    margin-top: -2vh;
    padding-right: 3vw;
    align-items: space-between;
    background-color: #565656;

    align-content: center;
     flex-wrap: wrap;

  }

#id_title,#id_organiser_email,#id_prize,#id_enddate,#id_poster,#id_guidlines
{
position: relative;
  width: 50vw;
  margin-left: 5vw;
  background-color :white;
        color :blue;
        border-radius:25px;

}
#id_description
{
  position: relative;
  margin-left:5vw;
  width: 50vw;
  height: 20vh;
  border-radius:25px;

}

@media only screen and (max-width: 800px)
{

#id_Fullname,#id_about,#id_mobile,#id_email,#id_dob,#id_address,#id_image,#id_resume
{
  position: relative;
  width: 70vw;
  margin-left: 10vw;
  background-color :white;
        color :blue;

}
#id_about,#id_address
{
  height: 20vw;
  background-color :white;
        color :blue;

}
  #t
    {
      margin-left: 10vw;
      width:70vw;
      margin-top: -5vh;
        font-size:0.7em;




    }
    #emaildes
    {
        font-size:0.5em;

    }



  }
    #emaildes
    {

        color:#565656;
    }

</style>
<h3 id="t" class="alert alert-success">ORGANISE CONTEST</h3>

{% if messages %}
<div class="alert alert-success alert-dismissible">
  {% for message in messages %}
    <p>{{ message }}</p>
  {% endfor %}
</div>
{% endif %}


<form method="POST" action="{% url 'organisecontest' %}"   style="color: white; "enctype="multipart/form-data">
  {% csrf_token %}










<br>
<!--Full Name          :  &nbsp  &nbsp  --> {{form.title}}
<br>
<!--email         : &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  --> {{form.organiser_email}}


<br>
<!--Address       : &nbsp &nbsp &nbsp &nbsp -->  {{form.prize}}
<br>
 {{form.enddate}}
<br>
<p style="color:black;margin-left:5vw;">Desciption</p>
  {{form.description}}
<br>
<p style="color:black;margin-left:5vw;">Poster Image</p>
 {{form.poster}}
<br>
<p style="color:black;margin-left:5vw;">Guidline PDF</p>
 {{form.guidlines}}
<br>
  <button  action="{% url 'organisecontest' %}" class="btn btn-success" style="margin-left:30vw;" type="submit">Organise</button>

</form>
  <script>
            /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field
     */

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[2].placeholder='title..';
    form_fields[3].placeholder='Organiser Email..';

    form_fields[4].placeholder='Total prize...';
    form_fields[5].placeholder='Contest End date';

    form_fields[7].placeholder='description';
    



    for (var field in form_fields){
      form_fields[field].className += ' form-control'
    }
  </script>

{% endblock %}

contest/templates/contest/participate_contest.html
{% extends 'contest/base.html' %}

{% block content %}
{% if error %}
<script type="text/javascript">
  alert('{{error}}')
</script>
   {% endif %}


<style type="text/css">

body {
 /* background-image: url('https://cdn.dribbble.com/users/722246/screenshots/11096994/media/abcf2fe91c135bbaec19a3816dd0a992.gif');
  background-repeat: repeat-y;
  background-size: 100vw 100vh;*/
  background-color: #f6f6f6;
  margin-top: 0vw;
  color: white;
}

  #t
  {
       background-color : black;
      color :white;

       margin-left: 0vw;
      margin-top: 0vh;
      width: 60vw;
      border-radius:45px;
  }



  .flex-container_up{
    display: flex;
    margin: 5vw;
    margin-top: -2vh;
    padding-right: 3vw;
    align-items: space-between;
    background-color: #565656;

    align-content: center;
     flex-wrap: wrap;

  }

#id_participant_email
{
  position: relative;
  width: 50vw;
  margin-left: 5vw;
  background-color :white;
        color :blue;
        border-radius:25px;

}
#id_description
{
   margin-left: 5vw;
  width: 50vw;
  height: 15vh;
  background-color :white;
        color :blue;

}
#id_document
{
   margin-left: 5vw;
  width: 50vw;
}
@media only screen and (max-width: 800px)
{

#id_participant_email
{
  position: relative;
  width: 80vw;
  margin-left: 5vw;
  background-color :white;
        color :blue;
        border-radius:25px;

}
#id_description
{
  width: 80vw;
  height: 15vh;
  background-color :white;
        color :blue;

}

  #t
    {
      margin-left: 10vw;
      width:70vw;
      margin-top: -5vh;
        font-size:0.7em;




    }
    #emaildes
    {
        font-size:0.5em;

    }



  }
    #emaildes
    {

        color:#565656;
    }

</style>
<h3 id="t" class="alert alert-success">{{contest.title}}</h3>

{% if messages %}
<div class="alert alert-success alert-dismissible">
  {% for message in messages %}
    <p>{{ message }}</p>
  {% endfor %}
</div>
{% endif %}


<form method="POST" action="{% url 'submitcontest' contest.id %}"   style="color: white; "enctype="multipart/form-data">
  {% csrf_token %}










<p style="color:black;margin-left:5vw;">Email</p>


<!--email         : &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  --> {{form.participant_email}}

<br>
<br>

<p style="color:black;margin-left:5vw;">Desciption</p>
  {{form.description}}
<br>
<br>
<p style="color:black;margin-left:5vw;">Submit your Design</p>
 {{form.document}}
<br>
 <button method="POST" action="{% url 'submitcontest' contest.id %}" type="submit"  class="btn btn-success" style="margin-left:30vw;" type="submit">Submit</button>


</form>
  <script>
            /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field
     */

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')

form_fields[1].placeholder='Desciption';
    form_fields[2].placeholder='Enter your registered email';




    for (var field in form_fields){
      form_fields[field].className += ' form-control'
    }
  </script>

{% endblock %}

contest/templates/contest/request_organise_contest_email.html
{% autoescape off %}
Dear Sir/Ma’am,

It makes us really happy that you are interested in hosting contest with us. We’ve received your details and our team will contact you soon. Provided details are as follows:

Name: {{name}}
Email: {{email}}
Description: {{bio}}
Mobile No.: {{mobile}}
Website: {{website}}

You can also mail us at: spamelectryc@gmail.com.

Thank You! for reaching out to us.
Team vcreate

{% endautoescape %}